# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d280b9aad6db790f918fd879596061530db2f665536cc1d7f9dbc62427249c18d1feac7f7a9eaf689d7c7d95f68db15d052d790b7d93ba2f6cf002def4734de

test:
  secret_key_base: 41ac7016910fccd1ce8b7ac08a3ac6dbbcb6aab46089b3d89fae652913f53d5f92dd8de00486bc72238a4384780b4d01a5dc5b03186c5f39987fa23e2c5e5c98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
